name: Testing

on: push

jobs:
    mockserver-test:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [11, 12, 13, 14]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.nodejs }}
            - name: install dependencies
              run: npm install
            - name: run tests
              run: npm test
            - name: Codecov
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: unittests
